#############################################################################
# Makefile for building: Touch
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  Touch.pro
# Template: app
# Command: /mnt/rasp-pi-rootfs/usr/local/qt5pi/bin/qmake -spec devices/linux-rasp-pi-g++ CONFIG+=debug -o Makefile Touch.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /home/chalumpol/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc
CXX           = /home/chalumpol/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/mnt/rasp-pi-rootfs -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/mnt/rasp-pi-rootfs -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/mnt/rasp-pi-rootfs/usr/local/qt5pi/include -I/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets -I/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui -I/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore -I. -I/mnt/rasp-pi-rootfs/opt/vc/include -I/mnt/rasp-pi-rootfs/opt/vc/include/interface/vcos/pthreads -I/mnt/rasp-pi-rootfs/opt/vc/include/interface/vmcs_host/linux -I. -I/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi-g++
QMAKE         = /mnt/rasp-pi-rootfs/usr/local/qt5pi/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Touch1.0.0
DISTDIR = /home/chalumpol/Touch/.tmp/Touch1.0.0
LINK          = /home/chalumpol/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-rpath-link,/mnt/rasp-pi-rootfs/opt/vc/lib -Wl,-rpath-link,/mnt/rasp-pi-rootfs/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/mnt/rasp-pi-rootfs/lib/arm-linux-gnueabihf -mfloat-abi=hard --sysroot=/mnt/rasp-pi-rootfs -Wl,-rpath,/usr/local/qt5pi/lib
LIBS          = $(SUBLIBS) -L/mnt/rasp-pi-rootfs/opt/vc/lib -L/mnt/rasp-pi-rootfs/usr/local/qt5pi/lib -lQt5Widgets -L/home/chalumpol/opt/tslib/build/lib/ -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
AR            = /home/chalumpol/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/chalumpol/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/spec_pre.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/unix.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/linux.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/sanitize.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/gcc-base.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/gcc-base-unix.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/g++-base.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/g++-unix.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/qdevice.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/device_config.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/common/linux_device_pre.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/common/linux_device_post.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/common/linux_arm_device_post.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/qconfig.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_core.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_core_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_gui.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_gui_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_network.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_network_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_sql.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_sql_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xml.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xml_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/qt_functions.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/qt_config.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/spec_post.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/exclusive_builds.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/default_pre.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/resolve_config.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/default_post.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/warn_on.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/qt.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/resources.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/moc.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/unix/opengl.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/uic.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/unix/thread.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/testcase_targets.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/exceptions.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/yacc.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/lex.prf \
		Touch.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = Touch
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Touch


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Touch.pro /mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi-g++/qmake.conf /mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/spec_pre.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/unix.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/linux.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/sanitize.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/gcc-base.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/gcc-base-unix.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/g++-base.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/g++-unix.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/qdevice.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/device_config.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/common/linux_device_pre.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/common/linux_device_post.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/common/linux_arm_device_post.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/qconfig.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_core.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_core_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_gui.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_gui_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_network.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_network_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_sql.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_sql_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xml.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xml_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/qt_functions.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/qt_config.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/spec_post.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/exclusive_builds.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/default_pre.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/resolve_config.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/default_post.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/warn_on.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/qt.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/resources.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/moc.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/unix/opengl.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/uic.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/unix/thread.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/testcase_targets.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/exceptions.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/yacc.prf \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/lex.prf \
		Touch.pro \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/lib/libQt5Widgets.prl \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/lib/libQt5Gui.prl \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/lib/libQt5Core.prl
	$(QMAKE) -spec devices/linux-rasp-pi-g++ CONFIG+=debug -o Makefile Touch.pro
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/spec_pre.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/unix.conf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/linux.conf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/sanitize.conf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/gcc-base.conf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/gcc-base-unix.conf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/g++-base.conf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/common/g++-unix.conf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/qdevice.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/device_config.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/common/linux_device_pre.conf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/common/linux_device_post.conf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/common/linux_arm_device_post.conf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/qconfig.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_concurrent_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_core.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_core_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_dbus_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_gui.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_gui_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_network.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_network_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_opengl_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_openglextensions_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_platformsupport_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_printsupport_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_sql.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_sql_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_testlib_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_widgets_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xml.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xml_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/qt_functions.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/qt_config.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi-g++/qmake.conf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/spec_post.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/exclusive_builds.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/default_pre.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/resolve_config.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/default_post.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/warn_on.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/qt.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/resources.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/moc.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/unix/opengl.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/uic.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/unix/thread.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/testcase_targets.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/exceptions.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/yacc.prf:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/features/lex.prf:
Touch.pro:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/lib/libQt5Widgets.prl:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/lib/libQt5Gui.prl:
/mnt/rasp-pi-rootfs/usr/local/qt5pi/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec devices/linux-rasp-pi-g++ CONFIG+=debug -o Makefile Touch.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QMainWindow \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qmainwindow.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qwidget.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qwindowdefs.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qglobal.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qconfig.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qfeatures.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsystemdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qprocessordetection.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcompilerdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qtypeinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qtypetraits.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsysinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qlogging.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qflags.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qbasicatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qgenericatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_cxx11.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_gcc.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_msvc.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_armv7.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_armv6.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_armv5.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_ia64.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_mips.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_x86.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_unix.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qglobalstatic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmutex.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qnumeric.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobjectdefs.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qnamespace.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qwindowdefs_win.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobject.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstring.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qchar.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qbytearray.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qrefcount.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qarraydata.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstringbuilder.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qlist.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qalgorithms.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qiterator.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qbytearraylist.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstringlist.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qregexp.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstringmatcher.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcoreevent.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qscopedpointer.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmetatype.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qvarlengtharray.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcontainerfwd.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qisenum.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobject_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmargins.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpaintdevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qrect.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsize.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qpoint.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpalette.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qcolor.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qrgb.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qbrush.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qpair.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qvector.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qmatrix.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpolygon.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qregion.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qdatastream.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qiodevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qline.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qtransform.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpainterpath.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qimage.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpixelformat.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpixmap.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsharedpointer.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qshareddata.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qhash.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qfont.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qfontmetrics.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qfontinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qsizepolicy.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qcursor.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qkeysequence.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qevent.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qvariant.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmap.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qdebug.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qtextstream.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qlocale.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qset.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcontiguouscache.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qurl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qurlquery.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qfile.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qfiledevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qvector2d.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qtouchdevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qtabwidget.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qicon.h \
		mainwindow.h
	/mnt/rasp-pi-rootfs/usr/local/qt5pi/bin/moc $(DEFINES) -I/mnt/rasp-pi-rootfs/usr/local/qt5pi/mkspecs/devices/linux-rasp-pi-g++ -I/home/chalumpol/Touch -I/mnt/rasp-pi-rootfs/usr/local/qt5pi/include -I/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets -I/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui -I/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore -I/home/chalumpol/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3 -I/home/chalumpol/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/home/chalumpol/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/home/chalumpol/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/home/chalumpol/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/home/chalumpol/opt/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include -I/mnt/rasp-pi-rootfs/usr/include -I/mnt/rasp-pi-rootfs/usr/include/arm-linux-gnueabihf mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/mnt/rasp-pi-rootfs/usr/local/qt5pi/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QMainWindow \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qmainwindow.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qwidget.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qwindowdefs.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qglobal.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qconfig.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qfeatures.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsystemdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qprocessordetection.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcompilerdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qtypeinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qtypetraits.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsysinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qlogging.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qflags.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qbasicatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qgenericatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_cxx11.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_gcc.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_msvc.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_armv7.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_armv6.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_armv5.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_ia64.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_mips.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_x86.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_unix.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qglobalstatic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmutex.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qnumeric.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobjectdefs.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qnamespace.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qwindowdefs_win.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobject.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstring.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qchar.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qbytearray.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qrefcount.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qarraydata.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstringbuilder.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qlist.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qalgorithms.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qiterator.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qbytearraylist.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstringlist.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qregexp.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstringmatcher.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcoreevent.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qscopedpointer.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmetatype.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qvarlengtharray.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcontainerfwd.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qisenum.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobject_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmargins.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpaintdevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qrect.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsize.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qpoint.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpalette.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qcolor.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qrgb.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qbrush.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qpair.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qvector.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qmatrix.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpolygon.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qregion.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qdatastream.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qiodevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qline.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qtransform.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpainterpath.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qimage.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpixelformat.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpixmap.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsharedpointer.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qshareddata.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qhash.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qfont.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qfontmetrics.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qfontinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qsizepolicy.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qcursor.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qkeysequence.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qevent.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qvariant.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmap.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qdebug.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qtextstream.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qlocale.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qset.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcontiguouscache.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qurl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qurlquery.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qfile.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qfiledevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qvector2d.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qtouchdevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qtabwidget.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qicon.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QApplication \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qapplication.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcoreapplication.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qeventloop.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qdesktopwidget.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qguiapplication.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QMainWindow \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qmainwindow.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qwidget.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qwindowdefs.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qglobal.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qconfig.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qfeatures.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsystemdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qprocessordetection.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcompilerdetection.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qtypeinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qtypetraits.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsysinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qlogging.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qflags.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qbasicatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qgenericatomic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_cxx11.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_gcc.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_msvc.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_armv7.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_armv6.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_armv5.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_ia64.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_mips.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_x86.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qatomic_unix.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qglobalstatic.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmutex.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qnumeric.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobjectdefs.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qnamespace.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qwindowdefs_win.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobject.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstring.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qchar.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qbytearray.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qrefcount.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qarraydata.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstringbuilder.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qlist.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qalgorithms.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qiterator.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qbytearraylist.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstringlist.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qregexp.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qstringmatcher.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcoreevent.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qscopedpointer.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmetatype.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qvarlengtharray.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcontainerfwd.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qisenum.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qobject_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmargins.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpaintdevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qrect.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsize.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qpoint.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpalette.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qcolor.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qrgb.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qbrush.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qpair.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qvector.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qmatrix.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpolygon.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qregion.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qdatastream.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qiodevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qline.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qtransform.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpainterpath.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qimage.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpixelformat.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qpixmap.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsharedpointer.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qshareddata.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qhash.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qfont.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qfontmetrics.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qfontinfo.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qsizepolicy.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qcursor.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qkeysequence.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qevent.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qvariant.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qmap.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qdebug.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qtextstream.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qlocale.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qset.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcontiguouscache.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qurl.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qurlquery.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qfile.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qfiledevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qvector2d.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qtouchdevice.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qtabwidget.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qicon.h \
		ui_mainwindow.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/QVariant \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QAction \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qaction.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qactiongroup.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QApplication \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qapplication.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qcoreapplication.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qeventloop.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qdesktopwidget.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qguiapplication.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qinputmethod.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QButtonGroup \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qbuttongroup.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QHeaderView \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qheaderview.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qabstractitemview.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qabstractscrollarea.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qframe.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qabstractitemmodel.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qitemselectionmodel.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qabstractitemdelegate.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qstyleoption.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qabstractspinbox.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtGui/qvalidator.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/qregularexpression.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qslider.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qabstractslider.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qstyle.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qtabbar.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qrubberband.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QLabel \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qlabel.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QMenuBar \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qmenubar.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qmenu.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QPushButton \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qpushbutton.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qabstractbutton.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QStatusBar \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qstatusbar.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QToolBar \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/qtoolbar.h \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtWidgets/QWidget \
		/mnt/rasp-pi-rootfs/usr/local/qt5pi/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/pi || mkdir -p $(INSTALL_ROOT)/home/pi
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/pi/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/pi/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/pi/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

